name: Filename Sanitize (auto-fix)

on:
  push:
    branches: ["**"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sanitize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run sanitizer
        run: python3 .github/sanitize_filenames.py

      - name: Commit & push if changes
        run: |
          if ! git diff --quiet; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "chore: sanitize filenames for cross-platform compatibility"
            git push
          else
            echo "No changes to commit."
          fi
